name: Auto Grading

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas pytest

      - name: Run Tests
        id: run_tests
        run: |
            pytest --tb=short | tee report.txt
            
            # Extract number of collected tests safely
            total_tests=$(grep -oE 'collected [0-9]+' report.txt | awk '{print $2}')
            passed_tests=$(grep -c 'PASSED' report.txt)

            # Ensure values are numeric; default to 0 if empty
            total_tests=${total_tests:-0}
            passed_tests=${passed_tests:-0}

            # Debugging output to confirm extracted values
            echo "Extracted total_tests=$total_tests"
            echo "Extracted passed_tests=$passed_tests"

            # Calculate marks safely
            if [ "$total_tests" -eq 0 ]; then
                marks=0
            else
                marks=$(echo "scale=2; ($passed_tests * 100) / $total_tests" | bc)
            fi

            echo "Total Tests: $total_tests" >> report.txt
            echo "Passed Tests: $passed_tests" >> report.txt
            echo "Marks: $marks%" >> report.txt

            echo "marks=$marks" >> $GITHUB_ENV  # Updated to use environment variables
  

      - name: Commit Test Results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git add report.txt
          git commit -m "Updated test results" || echo "No changes to commit"

          git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git
          git push origin main
